"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { motion } from "framer-motion";
import {
  FileText,
  FileSpreadsheet,
  CheckCircle2,
  Clock,
  Globe,
  MapPin,
  MessageCircle,
  Mail,
  Link2,
  Download,
  Share2,
  Search,
  Inbox,
  Sparkles,
  ScanLine,
  XCircle,
  ChevronDown,
  Filter,
  Loader2,
  CheckSquare,
  Square,
  Languages,
} from "lucide-react";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  getAllScans,
  getPdfReportUrl,
  getExcelReportUrl,
  getGeoJSONUrl,
  getKMLUrl,
  type ReportLang,
} from "@/lib/api";
import type { ScanListItem } from "@/lib/types";
import { toast } from "sonner";

type StatusFilter = "all" | "completed" | "processing" | "failed";

export default function ReportsPage() {
  const [scans, setScans] = useState<ScanListItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");
  const [statusFilter, setStatusFilter] = useState<StatusFilter>("all");
  const [selected, setSelected] = useState<Set<string>>(new Set());

  useEffect(() => {
    getAllScans()
      .then((data) => {
        setScans(data.scans || []);
        setLoading(false);
      })
      .catch(() => setLoading(false));
  }, []);

  const stats = useMemo(() => {
    const total = scans.length;
    const completed = scans.filter((s) => s.status === "completed").length;
    const processing = scans.filter((s) => s.status === "processing").length;
    const failed = scans.filter(
      (s) => s.status !== "completed" && s.status !== "processing"
    ).length;
    return { total, completed, processing, failed };
  }, [scans]);

  const filteredScans = useMemo(() => {
    let list = scans;
    if (statusFilter !== "all") {
      if (statusFilter === "failed") {
        list = list.filter(
          (s) => s.status !== "completed" && s.status !== "processing"
        );
      } else {
        list = list.filter((s) => s.status === statusFilter);
      }
    }
    const q = search.trim().toLowerCase();
    if (q) {
      list = list.filter((s) => s.filename.toLowerCase().includes(q));
    }
    return list;
  }, [scans, statusFilter, search]);

  const allFilteredSelected =
    filteredScans.length > 0 &&
    filteredScans.every((s) => selected.has(s.scan_id));

  const downloadReport = (
    scanId: string,
    type: "pdf" | "excel" | "geojson" | "kml"
  ) => {
    const urlMap = {
      pdf: getPdfReportUrl(scanId),
      excel: getExcelReportUrl(scanId),
      geojson: getGeoJSONUrl(scanId),
      kml: getKMLUrl(scanId),
    };
    window.open(urlMap[type], "_blank");
    toast.success(`${type.toUpperCase()} download started`);
  };

  const downloadPdf = (scanId: string, lang: ReportLang) => {
    window.open(getPdfReportUrl(scanId, lang), "_blank");
    const labelMap: Record<ReportLang, string> = {
      en: "English",
      hi: "Hindi",
      bilingual: "Bilingual",
    };
    toast.success(`${labelMap[lang]} PDF download started`);
  };

  const buildShareMessage = (scan: ScanListItem) => {
    const pdfUrl =
      typeof window !== "undefined"
        ? new URL(
            getPdfReportUrl(scan.scan_id),
            window.location.origin
          ).toString()
        : getPdfReportUrl(scan.scan_id);
    const date = new Date(scan.created_at).toLocaleString();
    const score =
      scan.avg_retro_score != null
        ? scan.avg_retro_score.toFixed(1)
        : "N/A";
    return `RetroScan AI Report — ${scan.filename}

Scan completed: ${date}
Total assets: ${scan.total_detections}
Compliant: ${scan.compliance_pass} | Non-compliant: ${scan.compliance_fail}
Avg score: ${score}/100

Download report: ${pdfUrl}
Generated by RetroScan AI - NHAI Innovation Hackathon`;
  };

  const shareWhatsApp = (scan: ScanListItem) => {
    const text = encodeURIComponent(buildShareMessage(scan));
    window.open(`https://wa.me/?text=${text}`, "_blank");
    toast.success("Opening WhatsApp...");
  };

  const shareEmail = (scan: ScanListItem) => {
    const subject = encodeURIComponent(
      `RetroScan AI Report — ${scan.filename}`
    );
    const body = encodeURIComponent(buildShareMessage(scan));
    window.location.href = `mailto:?subject=${subject}&body=${body}`;
    toast.success("Opening email client...");
  };

  const copyLink = async (scan: ScanListItem) => {
    const pdfUrl =
      typeof window !== "undefined"
        ? new URL(
            getPdfReportUrl(scan.scan_id),
            window.location.origin
          ).toString()
        : getPdfReportUrl(scan.scan_id);
    try {
      if (navigator.clipboard?.writeText) {
        await navigator.clipboard.writeText(pdfUrl);
      } else {
        const ta = document.createElement("textarea");
        ta.value = pdfUrl;
        ta.style.position = "fixed";
        ta.style.opacity = "0";
        document.body.appendChild(ta);
        ta.select();
        document.execCommand("copy");
        document.body.removeChild(ta);
      }
      toast.success("Link copied!");
    } catch {
      toast.error("Failed to copy link");
    }
  };

  const toggleOne = (scanId: string) => {
    setSelected((prev) => {
      const next = new Set(prev);
      if (next.has(scanId)) next.delete(scanId);
      else next.add(scanId);
      return next;
    });
  };

  const toggleAll = () => {
    setSelected((prev) => {
      if (allFilteredSelected) {
        const next = new Set(prev);
        for (const s of filteredScans) next.delete(s.scan_id);
        return next;
      }
      const next = new Set(prev);
      for (const s of filteredScans) {
        if (s.status === "completed") next.add(s.scan_id);
      }
      return next;
    });
  };

  const bulkDownloadPdf = () => {
    const ids = Array.from(selected);
    if (ids.length === 0) {
      toast.error("Select at least one scan");
      return;
    }
    let count = 0;
    for (const id of ids) {
      const scan = scans.find((s) => s.scan_id === id);
      if (!scan || scan.status !== "completed") continue;
      window.open(getPdfReportUrl(id), "_blank");
      count++;
    }
    toast.success(`Started ${count} PDF download${count === 1 ? "" : "s"}`);
  };

  const bulkDownloadExcel = () => {
    const ids = Array.from(selected);
    if (ids.length === 0) {
      toast.error("Select at least one scan");
      return;
    }
    let count = 0;
    for (const id of ids) {
      const scan = scans.find((s) => s.scan_id === id);
      if (!scan || scan.status !== "completed") continue;
      window.open(getExcelReportUrl(id), "_blank");
      count++;
    }
    toast.success(`Started ${count} Excel download${count === 1 ? "" : "s"}`);
  };

  return (
    <div className="mx-auto max-w-7xl px-4 py-6 sm:px-6 sm:py-8 space-y-6">
      {/* Hero header */}
      <motion.div
        initial={{ opacity: 0, y: 12 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.3, ease: "easeOut" }}
      >
        <Card className="overflow-hidden border-border/40 bg-gradient-to-br from-emerald-500/[0.06] via-cyan-500/[0.04] to-transparent">
          <CardContent className="grid gap-6 p-6 sm:grid-cols-[1fr_auto] sm:items-center">
            <div className="flex items-start gap-4">
              <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-emerald-500/20 to-cyan-500/20 ring-1 ring-emerald-500/30">
                <FileText className="h-6 w-6 text-emerald-400" />
              </div>
              <div>
                <div className="inline-flex items-center gap-1.5 rounded-full bg-emerald-500/10 px-2.5 py-0.5 text-[11px] font-medium text-emerald-400 mb-2">
                  <Sparkles className="h-3 w-3" />
                  Reports & Exports
                </div>
                <h1 className="text-2xl sm:text-3xl font-bold tracking-tight">
                  IRC Compliance Reports
                </h1>
                <p className="text-sm text-muted-foreground mt-1 max-w-xl">
                  Generate, share, and archive bilingual PDF reports, Excel
                  exports, and GIS-ready KML/GeoJSON files.
                </p>
              </div>
            </div>
            <div className="grid grid-cols-3 gap-3 sm:gap-5 sm:min-w-[320px]">
              <SummaryStat
                label="Total"
                value={stats.total}
                tone="foreground"
              />
              <SummaryStat
                label="Completed"
                value={stats.completed}
                tone="emerald"
              />
              <SummaryStat
                label="Pending"
                value={stats.processing + stats.failed}
                tone="amber"
              />
            </div>
          </CardContent>
        </Card>
      </motion.div>

      {/* Report type cards */}
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <ReportTypeCard
          icon={FileText}
          title="PDF Report"
          description="IRC 67 & IRC 35 compliance — bilingual EN/HI, ready for officers."
          gradient="from-rose-500/20 to-rose-600/20"
          iconBg="from-red-500 to-rose-600"
          delay={0.05}
        />
        <ReportTypeCard
          icon={FileSpreadsheet}
          title="Excel Export"
          description="Full data with summary + per-detection sheets for analysis."
          gradient="from-emerald-500/20 to-teal-600/20"
          iconBg="from-emerald-500 to-teal-600"
          delay={0.1}
        />
        <ReportTypeCard
          icon={Globe}
          title="KML"
          description="Color-coded placemarks for Google Earth & Google Maps."
          gradient="from-blue-500/20 to-indigo-600/20"
          iconBg="from-blue-500 to-indigo-600"
          delay={0.15}
        />
        <ReportTypeCard
          icon={MapPin}
          title="GeoJSON"
          description="Standard GeoJSON for QGIS, ArcGIS and Mapbox pipelines."
          gradient="from-amber-500/20 to-orange-600/20"
          iconBg="from-amber-500 to-orange-600"
          delay={0.2}
        />
      </div>

      {/* Scans Table */}
      <Card className="border-border/40 bg-card/50 backdrop-blur">
        <CardHeader>
          <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
            <div>
              <CardTitle className="text-base">Scans</CardTitle>
              <CardDescription>
                Filter, search and export across all your scans.
              </CardDescription>
            </div>
            <div className="flex flex-col gap-2 sm:flex-row sm:items-center">
              <div className="relative">
                <Search className="absolute left-2.5 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-muted-foreground" />
                <Input
                  placeholder="Search by filename..."
                  value={search}
                  onChange={(e) => setSearch(e.target.value)}
                  className="pl-8 sm:w-56"
                />
              </div>
              <Select
                value={statusFilter}
                onValueChange={(v) => setStatusFilter(v as StatusFilter)}
              >
                <SelectTrigger className="w-full sm:w-40">
                  <Filter className="h-3.5 w-3.5 text-muted-foreground" />
                  <SelectValue placeholder="Status" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All statuses</SelectItem>
                  <SelectItem value="completed">Completed</SelectItem>
                  <SelectItem value="processing">Processing</SelectItem>
                  <SelectItem value="failed">Failed</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          {/* Bulk actions bar */}
          {selected.size > 0 && (
            <motion.div
              initial={{ opacity: 0, y: -4 }}
              animate={{ opacity: 1, y: 0 }}
              className="mt-4 flex flex-wrap items-center gap-3 rounded-lg border border-emerald-500/30 bg-emerald-500/5 px-3 py-2"
            >
              <Badge
                variant="outline"
                className="border-emerald-500/40 text-emerald-400"
              >
                {selected.size} selected
              </Badge>
              <Button
                variant="outline"
                size="sm"
                className="gap-1.5"
                onClick={bulkDownloadPdf}
              >
                <Download className="h-3.5 w-3.5" />
                PDFs
              </Button>
              <Button
                variant="outline"
                size="sm"
                className="gap-1.5"
                onClick={bulkDownloadExcel}
              >
                <FileSpreadsheet className="h-3.5 w-3.5" />
                Excel
              </Button>
              <Button
                variant="ghost"
                size="sm"
                onClick={() => setSelected(new Set())}
                className="ml-auto"
              >
                Clear
              </Button>
            </motion.div>
          )}
        </CardHeader>
        <CardContent>
          {loading ? (
            <SkeletonRows />
          ) : scans.length === 0 ? (
            <EmptyState />
          ) : filteredScans.length === 0 ? (
            <NoResultsState
              onClear={() => {
                setSearch("");
                setStatusFilter("all");
              }}
            />
          ) : (
            <div className="overflow-x-auto">
              <Table>
                <TableHeader>
                  <TableRow className="border-border/40 hover:bg-transparent">
                    <TableHead className="w-10">
                      <button
                        type="button"
                        onClick={toggleAll}
                        className="flex items-center justify-center text-muted-foreground hover:text-foreground transition-colors"
                        aria-label="Select all"
                      >
                        {allFilteredSelected ? (
                          <CheckSquare className="h-4 w-4 text-emerald-400" />
                        ) : (
                          <Square className="h-4 w-4" />
                        )}
                      </button>
                    </TableHead>
                    <TableHead>File</TableHead>
                    <TableHead>Status</TableHead>
                    <TableHead className="text-center">Detections</TableHead>
                    <TableHead className="text-center">Pass</TableHead>
                    <TableHead className="text-center">Fail</TableHead>
                    <TableHead className="text-center">Score</TableHead>
                    <TableHead className="text-right">Actions</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {filteredScans.map((scan, i) => (
                    <motion.tr
                      key={scan.scan_id}
                      initial={{ opacity: 0, y: 4 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{
                        duration: 0.25,
                        ease: "easeOut",
                        delay: Math.min(i * 0.02, 0.2),
                      }}
                      className="border-b border-border/40 transition-colors data-[state=selected]:bg-muted hover:bg-muted/30"
                    >
                      <TableCell className="w-10">
                        <button
                          type="button"
                          onClick={() => toggleOne(scan.scan_id)}
                          disabled={scan.status !== "completed"}
                          className="flex items-center justify-center text-muted-foreground hover:text-foreground transition-colors disabled:opacity-30 disabled:pointer-events-none"
                          aria-label="Select row"
                        >
                          {selected.has(scan.scan_id) ? (
                            <CheckSquare className="h-4 w-4 text-emerald-400" />
                          ) : (
                            <Square className="h-4 w-4" />
                          )}
                        </button>
                      </TableCell>
                      <TableCell>
                        <div className="flex items-center gap-3">
                          <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-md bg-muted/60 ring-1 ring-border/40">
                            <FileText className="h-3.5 w-3.5 text-muted-foreground" />
                          </div>
                          <div className="min-w-0">
                            <p className="font-medium text-sm truncate max-w-[220px]">
                              {scan.filename}
                            </p>
                            <p className="text-[11px] text-muted-foreground tabular-nums">
                              {new Date(scan.created_at).toLocaleString(
                                undefined,
                                {
                                  year: "numeric",
                                  month: "short",
                                  day: "numeric",
                                  hour: "2-digit",
                                  minute: "2-digit",
                                }
                              )}
                            </p>
                          </div>
                        </div>
                      </TableCell>
                      <TableCell>
                        <StatusBadge status={scan.status} />
                      </TableCell>
                      <TableCell className="text-center font-medium tabular-nums">
                        {scan.total_detections}
                      </TableCell>
                      <TableCell className="text-center text-emerald-400 font-medium tabular-nums">
                        {scan.compliance_pass}
                      </TableCell>
                      <TableCell className="text-center text-rose-400 font-medium tabular-nums">
                        {scan.compliance_fail}
                      </TableCell>
                      <TableCell className="text-center font-medium tabular-nums">
                        {scan.avg_retro_score?.toFixed(1) ?? "—"}
                      </TableCell>
                      <TableCell className="text-right">
                        <div className="flex gap-1.5 justify-end">
                          {/* Download Menu */}
                          <DropdownMenu>
                            <DropdownMenuTrigger
                              render={
                                <Button
                                  variant="outline"
                                  size="sm"
                                  disabled={scan.status !== "completed"}
                                  className="gap-1.5"
                                />
                              }
                            >
                              <Download className="h-3.5 w-3.5" />
                              Download
                              <ChevronDown className="h-3 w-3 opacity-60" />
                            </DropdownMenuTrigger>
                            <DropdownMenuContent align="end" className="w-56">
                              <DropdownMenuLabel className="flex items-center gap-1.5">
                                <Languages className="h-3 w-3" />
                                PDF Report
                              </DropdownMenuLabel>
                              <DropdownMenuItem
                                onClick={() =>
                                  downloadPdf(scan.scan_id, "en")
                                }
                              >
                                <span aria-hidden className="text-base">
                                  🇬🇧
                                </span>
                                English
                              </DropdownMenuItem>
                              <DropdownMenuItem
                                onClick={() =>
                                  downloadPdf(scan.scan_id, "hi")
                                }
                              >
                                <span aria-hidden className="text-base">
                                  🇮🇳
                                </span>
                                हिंदी (Hindi)
                              </DropdownMenuItem>
                              <DropdownMenuItem
                                onClick={() =>
                                  downloadPdf(scan.scan_id, "bilingual")
                                }
                              >
                                <span aria-hidden className="text-base">
                                  🌐
                                </span>
                                Bilingual (EN + HI)
                              </DropdownMenuItem>
                              <DropdownMenuSeparator />
                              <DropdownMenuLabel>Data exports</DropdownMenuLabel>
                              <DropdownMenuItem
                                onClick={() =>
                                  downloadReport(scan.scan_id, "excel")
                                }
                              >
                                <FileSpreadsheet className="h-3.5 w-3.5 text-emerald-400" />
                                Excel (.xlsx)
                              </DropdownMenuItem>
                              <DropdownMenuItem
                                onClick={() =>
                                  downloadReport(scan.scan_id, "kml")
                                }
                              >
                                <Globe className="h-3.5 w-3.5 text-blue-400" />
                                KML (Google Earth)
                              </DropdownMenuItem>
                              <DropdownMenuItem
                                onClick={() =>
                                  downloadReport(scan.scan_id, "geojson")
                                }
                              >
                                <MapPin className="h-3.5 w-3.5 text-amber-400" />
                                GeoJSON
                              </DropdownMenuItem>
                            </DropdownMenuContent>
                          </DropdownMenu>

                          {/* Share Menu */}
                          <DropdownMenu>
                            <DropdownMenuTrigger
                              render={
                                <Button
                                  size="sm"
                                  disabled={scan.status !== "completed"}
                                  className="gap-1.5"
                                />
                              }
                            >
                              <Share2 className="h-3.5 w-3.5" />
                              Share
                              <ChevronDown className="h-3 w-3 opacity-70" />
                            </DropdownMenuTrigger>
                            <DropdownMenuContent align="end" className="w-44">
                              <DropdownMenuItem
                                onClick={() => shareWhatsApp(scan)}
                              >
                                <MessageCircle className="h-3.5 w-3.5 text-[#25D366]" />
                                WhatsApp
                              </DropdownMenuItem>
                              <DropdownMenuItem
                                onClick={() => shareEmail(scan)}
                              >
                                <Mail className="h-3.5 w-3.5 text-blue-400" />
                                Email
                              </DropdownMenuItem>
                              <DropdownMenuSeparator />
                              <DropdownMenuItem
                                onClick={() => copyLink(scan)}
                              >
                                <Link2 className="h-3.5 w-3.5" />
                                Copy report link
                              </DropdownMenuItem>
                            </DropdownMenuContent>
                          </DropdownMenu>
                        </div>
                      </TableCell>
                    </motion.tr>
                  ))}
                </TableBody>
              </Table>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}

function SummaryStat({
  label,
  value,
  tone,
}: {
  label: string;
  value: number;
  tone: "foreground" | "emerald" | "amber";
}) {
  const colorMap = {
    foreground: "text-foreground",
    emerald: "text-emerald-400",
    amber: "text-amber-400",
  } as const;
  return (
    <div className="rounded-xl border border-border/40 bg-background/40 px-3 py-2 text-center backdrop-blur sm:text-left">
      <div className={`text-2xl font-bold tabular-nums ${colorMap[tone]}`}>
        {value}
      </div>
      <div className="text-[11px] uppercase tracking-wide text-muted-foreground">
        {label}
      </div>
    </div>
  );
}

function ReportTypeCard({
  icon: Icon,
  title,
  description,
  gradient,
  iconBg,
  delay = 0,
}: {
  icon: React.ComponentType<{ className?: string }>;
  title: string;
  description: string;
  gradient: string;
  iconBg: string;
  delay?: number;
}) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.3, delay, ease: "easeOut" }}
      whileHover={{ y: -3 }}
    >
      <Card
        className={`group relative h-full overflow-hidden border-border/40 bg-card/50 backdrop-blur transition-all duration-300 hover:ring-foreground/20`}
      >
        <div
          className={`pointer-events-none absolute -top-12 -right-12 h-32 w-32 rounded-full bg-gradient-to-br ${gradient} blur-2xl opacity-50 transition-opacity duration-300 group-hover:opacity-80`}
        />
        <CardContent className="relative flex flex-col gap-3 p-5">
          <div
            className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br ${iconBg} shadow-lg`}
          >
            <Icon className="h-5 w-5 text-white" />
          </div>
          <div>
            <h3 className="font-semibold text-sm">{title}</h3>
            <p className="text-xs text-muted-foreground mt-1 leading-relaxed">
              {description}
            </p>
          </div>
        </CardContent>
      </Card>
    </motion.div>
  );
}

function StatusBadge({ status }: { status: string }) {
  if (status === "completed") {
    return (
      <Badge
        variant="outline"
        className="gap-1.5 border-emerald-500/30 bg-emerald-500/5 text-emerald-400"
      >
        <span className="relative flex h-1.5 w-1.5">
          <span className="absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-50" />
          <span className="relative inline-flex h-1.5 w-1.5 rounded-full bg-emerald-400" />
        </span>
        <CheckCircle2 className="h-3 w-3" />
        Completed
      </Badge>
    );
  }
  if (status === "processing") {
    return (
      <Badge
        variant="outline"
        className="gap-1.5 border-amber-500/30 bg-amber-500/5 text-amber-400"
      >
        <span className="relative flex h-1.5 w-1.5">
          <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-amber-400 opacity-75" />
          <span className="relative inline-flex h-1.5 w-1.5 rounded-full bg-amber-400" />
        </span>
        <Clock className="h-3 w-3" />
        Processing
      </Badge>
    );
  }
  return (
    <Badge
      variant="outline"
      className="gap-1.5 border-rose-500/30 bg-rose-500/5 text-rose-400"
    >
      <span className="inline-block h-1.5 w-1.5 rounded-full bg-rose-400" />
      <XCircle className="h-3 w-3" />
      {status}
    </Badge>
  );
}

function SkeletonRows() {
  return (
    <div className="space-y-3">
      {Array.from({ length: 5 }).map((_, i) => (
        <div
          key={i}
          className="flex items-center gap-3 rounded-lg border border-border/40 px-3 py-3 animate-pulse"
        >
          <div className="h-8 w-8 rounded-md bg-muted/60" />
          <div className="flex-1 space-y-2">
            <div className="h-3 w-1/3 rounded bg-muted/60" />
            <div className="h-2 w-1/4 rounded bg-muted/40" />
          </div>
          <div className="h-6 w-20 rounded-full bg-muted/40" />
          <div className="h-8 w-24 rounded-md bg-muted/40" />
          <div className="h-8 w-20 rounded-md bg-muted/40" />
        </div>
      ))}
    </div>
  );
}

function EmptyState() {
  return (
    <div className="flex flex-col items-center justify-center gap-4 py-16 text-center">
      <div className="relative">
        <div className="absolute inset-0 rounded-full bg-emerald-500/10 blur-2xl" />
        <div className="relative flex h-16 w-16 items-center justify-center rounded-2xl bg-gradient-to-br from-emerald-500/20 to-cyan-500/20 ring-1 ring-emerald-500/30">
          <Inbox className="h-8 w-8 text-emerald-400" />
        </div>
      </div>
      <div>
        <h3 className="text-lg font-semibold">No reports yet</h3>
        <p className="text-sm text-muted-foreground mt-1 max-w-sm">
          Run your first scan and generate compliance-ready reports in
          seconds.
        </p>
      </div>
      <div className="flex flex-wrap items-center justify-center gap-2 pt-2">
        <Link href="/">
          <Button className="gap-1.5">
            <ScanLine className="h-3.5 w-3.5" />
            Start Scanning
          </Button>
        </Link>
        <Link href="/calibration">
          <Button variant="outline" className="gap-1.5">
            <Sparkles className="h-3.5 w-3.5" />
            View Sample Methodology
          </Button>
        </Link>
      </div>
    </div>
  );
}

function NoResultsState({ onClear }: { onClear: () => void }) {
  return (
    <div className="flex flex-col items-center justify-center gap-3 py-12 text-center">
      <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-muted/40">
        <Loader2 className="h-5 w-5 text-muted-foreground" />
      </div>
      <p className="text-sm text-muted-foreground">
        No scans match your filters.
      </p>
      <Button variant="outline" size="sm" onClick={onClear}>
        Clear filters
      </Button>
    </div>
  );
}
